services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - backend_node_modules:/app/node_modules
    ports:
      - "8080:8000"
    depends_on:
      - db
    
  db:
    image: postgres
    env_file:
      - ./db/.env.local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  frontend_node_modules:
  backend_node_modules:
  db_data: